#!/usr/bin/env bash

usage() {
    cat <<EOF
Usage: $0
This script will install fzf-help to /usr/share/zsh/plugins/fzf-help.

If the --bash option is given, it will install to /usr/share/fzf-help instead.

Options:
    --bash      Install to /usr/share/fzf-help instead of
                /usr/share/zsh/plugins/fzf-help
    -h, --help  Show this help message
EOF
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --user)
                plugin_dir="$HOME/.local/share/fzf-help"
                root=false
                shift
                ;;
            --zsh)
                shift
                ;;
            --bash)
                plugin_dir=/usr/share/fzf-help
                shift
                ;;
            -h | --help)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done
}

abort() {
    echo 'installation aborted'
    exit 1
}

remove_old() {
    remove="rm -rf $plugin_dir || abort"
    if [[ -d $plugin_dir ]]; then
        echo "Found old installation at $plugin_dir"
        echo "Deleting old installation..."
        if $root; then
            echo "Deleting as root"
            eval "sudo $remove"
        else
            echo "Deleting as user"
            eval $remove
        fi
        echo 'Uninstall complete.'
    else
        echo 'No old installation found.'
    fi
}

install() {
    echo "Copying fzf-help to $plugin_dir"
    makedir="mkdir -p $plugin_dir || abort"
    copy="cp $this_dir/src/* $plugin_dir || abort"
    if $root; then
        echo "Installing as root"
        eval "sudo $makedir"
        eval "sudo $copy"
    else
        echo "Installing as user"
        eval $makedir
        eval $copy
    fi
    echo 'Installation complete.'
}

this_dir=$(dirname $(realpath ${BASH_SOURCE:-$0}))
root=true
plugin_dir=/usr/share/zsh/plugins/fzf-help
parse_args $@
remove_old
install
