#!/usr/bin/env bash

usage() {
    cat <<EOF
Usage: $0
This script will install fzf-help to /usr/share/zsh/plugins/fzf-help.

If the --bash option is given, it will install to /usr/share/fzf-help instead.

Options:
    --bash      Install to /usr/share/fzf-help instead of
                /usr/share/zsh/plugins/fzf-help
    -h, --help  Show this help message
EOF
}

this_dir=$(dirname $(realpath ${BASH_SOURCE:-$0}))
plugin_dir=/usr/share/zsh/plugins/fzf-help
while [[ $# -gt 0 ]]; do
    case $1 in
        --bash)
            plugin_dir=/usr/share/fzf-help
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

abort() {
    echo 'installation aborted'
    exit 0
}

if [[ -d $plugin_dir ]]; then
    echo "Found old installation at $plugin_dir"
    echo "Deleting old installation..."
    sudo rm -rf $plugin_dir || abort
fi

echo "Copying fzf-help to $plugin_dir"
sudo mkdir $plugin_dir || abort
sudo cp $this_dir/src/* $plugin_dir || abort
echo 'Installation complete.'
