#!/usr/bin/env bash
this_dir=$(dirname $(realpath ${BASH_SOURCE:-$0}))
plugin_dir=/usr/share/zsh/plugins/fzf-help

abort() {
    echo 'installation aborted'
    exit 1
}

if [[ -d $plugin_dir ]]; then
    echo "Deleting old installation at: $plugin_dir"
    sudo rm -rf $plugin_dir || abort
else
    echo 'fzf-help is not installed.'
    exit 0
fi

echo 'Uninstall complete.'
