#!/usr/bin/env bash

usage() {
    cat <<EOF
Usage: $0
This script will uninstall fzf-help from /usr/share/zsh/plugins/fzf-help.

If the --bash option is given, it will uninstall /usr/share/fzf-help instead.

Options:
    --bash      Uninstall from /usr/share/fzf-help
    --fish      Uninstall from /usr/share/fzf-help and /etc/fish/functions/
    -h, --help  Show this help message
EOF
}

this_dir=$(dirname $(realpath ${BASH_SOURCE:-$0}))
plugin_dir=/usr/share/zsh/plugins/fzf-help
while [[ $# -gt 0 ]]; do
    case $1 in
        --bash)
            plugin_dir=/usr/share/fzf-help
            shift
            ;;
        --fish)
            plugin_dir=/usr/share/fzf-help
            function_dir=/etc/fish/functions/
            isfish=TRUE
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

abort() {
    echo 'Uninstallation aborted'
    exit 1
}

if [[ -d $plugin_dir ]]; then
    echo "Deleting old installation at: $plugin_dir"
    sudo rm -rf $plugin_dir || abort
    if [ ! -z "$isfish" ]; then 
      sudo rm -rf $function_dir/fzf-help.fish || abort
    fi
else
    echo 'fzf-help is not installed.'
    exit 0
fi

echo 'Uninstall complete.'
