#!/usr/bin/env bash
set -euo pipefail

usage="Usage: $(basename "$0") [-h | --help]

Returns the optional command line arguments that are present in stdin. The
options are extracted using the command that is defined in the CLI_OPTIONS_CMD
environment variable. If this variable is not set, the default command is used.

where:
    options:
    -h --help   shows this help messages"

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
        -h | --help)
            echo "$usage"
            exit 0
            ;;
        *)
            echo "Unknown argument: $1"
            echo "$usage"
            exit 1
            ;;
        esac
    done
}

# Support the ASCII hyphen and U+2010 hyphen forms.
LEFT_BOUNDARY='(?<![A-Za-z0-9_‐-])'
LONG_OPTION='(?:--|‐‐)[A-Za-z0-9][A-Za-z0-9_-]*'
SHORT_OPTION='(?:-|‐)[A-Za-z0-9?.:#@~]'

# \x27, \x22, and \x60 are the apostrophe, quotation mark, and backtick.
RIGHT_BOUNDARY='(?=$|\s|[\[\](){}<>=\x27\x22\x60]|[,;:.!?](?=$|\s|[-‐\])}>\x27\x22\x60])|[/|](?=[-‐]))'
RE="$LEFT_BOUNDARY(?:$LONG_OPTION|$SHORT_OPTION)$RIGHT_BOUNDARY"

# If on macOS check if GNU grep is installed as ggrep
if [[ "$(uname)" == "Darwin" ]] && [[ "$(command -v ggrep 2>/dev/null)" ]]; then
    GREP_CMD="ggrep"
fi

parse_args "$@"
cli_options_cmd="${CLI_OPTIONS_CMD:-"${GREP_CMD:-grep} -o --line-number -P -- \"$RE\""}"
eval "$cli_options_cmd"
