#!/usr/bin/env bash

usage="Usage: $(basename "$0") [-h | --help]

Returns the positional command line arguments that are present in stdin. The
options are extracted using the regex provided by the CLI_OPTIONS_REGEX
environment variable. If the regex is not provided, then the default regex is
used.

where:
    options:
    -h --help   shows this help messages"

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h | --help)
                echo "$usage"
                exit 0
                ;;
            *)
                echo "Unknown argument: $1"
                echo "$usage"
                exit 1
                ;;
        esac
        shift
    done
}

get_regex() {
    if [[ -z $CLI_OPTIONS_REGEX ]]; then
        PREFIX='(?<=[^\-])(--|‐‐)' # 2 different types of dashes, different key-codes
        HEAD='a-zA-Z0-9\['
        MIDDLE='a-zA-Z0-9\[\]\-\=\.\,\%'
        TAIL='a-zA-Z0-9'
        LONG="($PREFIX)([$HEAD]+[$MIDDLE]*[$TAIL]+)"

        PREFIX='(?<=[^\-a-zA-Z0-9])(-)'
        TAIL='[a-zA-Z]{1}'
        SHORT="($PREFIX)($TAIL)"

        CLI_OPTIONS_REGEX="$LONG|$SHORT"
    fi
    echo "$CLI_OPTIONS_REGEX"
}

parse_args "$@"
ag --only-matching --numbers -- "$(get_regex)"
