#!/usr/bin/env bash

usage="Usage: $(basename "$0") [-h | --help] <cmd>

Returns the positional command line arguments for <cmd>. Only long (--arg)
optional arguments are supported.

The regex used to extract the options can be overridden by setting the 
CLI_OPTIONS_REGEX environment variable.

where:
    options:
    -h --help   shows this help messages

    positional:
    <cmd>   an existing command"

options=$(getopt -o h --long help -- "$@")

[ $? -eq 0 ] || { echo "Incorrect options provided"; exit 1; }

eval set -- "$options"
while true; do
    case "$1" in
    -h | --help)
        echo "$usage"
        exit
        ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

[ $# -eq 0 ] && { echo "$usage"; exit ;}

cmd=$@

[[ -z $CLI_OPTIONS_CMD ]] && CLI_OPTIONS_CMD="$cmd --help" 

if [[ -z $CLI_OPTIONS_REGEX ]]; then
    PREFIX='(?<=[^\-])(--)'
    HEAD='a-zA-Z0-9\['
    MIDDLE='a-zA-Z0-9\[\]\-\=\.\,\%'
    TAIL='a-zA-Z0-9'
    LONG="($PREFIX)([$HEAD]+[$MIDDLE]*[$TAIL]+)"

    PREFIX='(?<=[^\-a-zA-Z0-9])(-)'
    TAIL='[a-zA-Z]{1}'
    SHORT="($PREFIX)($TAIL)"
    
    CLI_OPTIONS_REGEX="$LONG|$SHORT"
fi

eval $CLI_OPTIONS_CMD | ag --only-matching --numbers -- "$CLI_OPTIONS_REGEX"
