#!/usr/bin/env bash
set -euo pipefail

usage="Usage: $(basename "$0") [-h | --help] <cmd>

Displays the cli options for <cmd> using fzf, allowing the user to select one
of them. The options is send to stdout when it is accepted. In the preview
window, the selected option is highlighted and the help message for the option
is displayed. 

The <cmd> can also be provided via stdin. The <cmd> can also containt options
which will be stripped. For example, \`rm -rf\` will be treated as \`rm\`.

This program is intended to be used with the fzf-select-command program as the
function used for the fzf --preview option.

where:
    options:
    -h --help   shows this help messages
    -d --debug  

    positional:
    <cmd>   an existing command"

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h | --help)
                echo "$usage"
                exit 0
                ;;
            -d | --debug)
                fzf_cmd="fzf_debug"
                shift
                ;;
            -*)
                echo "Unknown option: $1"
                echo "$usage"
                exit 1
                ;;
            *)
                cmd="$1"
                shift
                ;;
        esac
    done

    if [[ -z $cmd ]]; then
        cmd="$(cat -)"
    fi

    cmd=$(get_command <<<"$cmd")
}

get_command() {
    sed "s/\( -\).*$//"
}

get_fzf_help_opts() {
    local default
    default="--multi --layout=reverse --preview-window=right,75%,wrap --height 80% "
    default+="--bind ctrl-a:change-preview-window(down,75%,nowrap|right,75%,nowrap)"
    fzf_help_opts="${FZF_HELP_OPTS:-$default}"
}

get_preview_cmd() {
    if [[ -z $opts ]]; then
        echo "echo \"No help page or options found for $cmd\""
    else
        # Uses the cached help message, see help-message.
        echo "$dir/help-message | $dir/fzf-select-option-preview \"$opts\" {n}"
    fi
}

remove_line_number() {
    sed "s/^.*://g"
}

fzf_debug() {
    local msg preview_cmd_no_path
    msg="stdin:\n$(cat -)\n"
    shift
    preview_cmd_no_path=${1//$dir\//}
    msg+="\npreview cmd:\n$preview_cmd_no_path\n"
    shift
    msg+="\nfzf_help_opts:\n${*}"
    echo -e "$msg"
}

cmd=""
fzf_cmd="fzf"
fzf_help_opts=""
parse_args "$@"
[[ -z $cmd ]] && echo "$usage" && exit 1

get_fzf_help_opts

dir=$(dirname "$(realpath "${BASH_SOURCE:-$0}")")
opts="$("$dir/help-message" "$cmd" | "$dir/cli-options")"
preview_cmd=$(get_preview_cmd)

remove_line_number <<<"$opts" | $fzf_cmd --preview "$preview_cmd" $fzf_help_opts
