#!/usr/bin/env bash

usage="Usage: $(basename "$0") [-h | --help] <cmd>

Displays the cli options for <cmd> using fzf, allowing the user to select one
of them. In the preview window, the selected option is highlighted and the help
message for the option is displayed.

The <cmd> can also be provided via stdin.

where:
    options:
    -h --help   shows this help messages

    positional:
    <cmd>   an existing command"

_get_command() {
    sed "s/\( -\).*$//"
}

_remove_line_number() {
    sed "s/^.*://g"
}

options=$(getopt -o h --long help -- "$@")
[ $? -eq 0 ] || { echo "Incorrect options provided"; exit 1; }

eval set -- "$options"
while true; do
    case "$1" in
    -h | --help)
        echo "$usage"
        exit
        ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

if [[ -p /dev/stdin ]]; then
    buffer="$(cat -)"
else
    buffer="${@}"
fi

[ $# -eq 0 ] && [ -z "$buffer" ] && { echo "$usage"; exit ;}

if [[ -z $FZF_HELP_OPTS ]]; then
    FZF_HELP_OPTS="--multi --preview-window=right,50%,nowrap --height 80% "
    FZF_HELP_OPTS+="--bind ctrl-a:change-preview-window(down,50%,nowrap|right,50%,nowrap)"
fi

cmd=$(echo $buffer | _get_command)
[[ -z $cmd ]] && exit 1

this_dir=$(dirname $(realpath ${BASH_SOURCE:-$0}))
help_msg='/tmp/fzf-select-option-help-msg.help'
$this_dir/help-message $cmd > $help_msg
opts="$(cat $help_msg | $this_dir/cli-options)"

echo "$opts" | _remove_line_number |
fzf --prompt="$buffer" \
    --preview "$this_dir/bat-cli-option \"$help_msg\" \"$opts\" {n}" \
    $FZF_HELP_OPTS
