#!/usr/bin/env bash
set -euo pipefail

_fzf_help_directory=$(dirname $(realpath "${BASH_SOURCE:-$0}"))
source "$_fzf_help_directory"/fzf-help-log

usage="Usage: $(basename "$0") [-h | --help] <cmd>

Writes the help message for <cmd> to stdout and a temp file. If no <cmd>
argument is given, it writes the content of the temp file to stdout. The file
contains the help message from the last command.

The default command is:

    <cmd> --help

When you set HELP_MESSAGE_CMD, fzf-help evaluates it as trusted Bash code. It
sets the \$cmd variable to the validated command name.

where:
    options:
    -h --help   shows this help messages

    positional:
    <cmd>   an existing command"

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h | --help)
                echo "$usage"
                exit 0
                ;;
            *)
                if [[ -z $cmd ]]; then
                    cmd="$1"
                else
                    echo "Unknown argument: $1"
                    echo "$usage"
                    exit 1
                fi
                ;;
        esac
        shift
    done
}

cmd=""
parse_args "$@"

if [[ -n $cmd && ! $cmd =~ ^[a-zA-Z0-9_.+-]+$ ]]; then
    echo "The command name contains unsupported characters." >&2
    exit 1
fi

help_message=$("$_fzf_help_directory"/make-temp "fzf-help-message")
help_message_cmd="${HELP_MESSAGE_CMD:-}"
help_message_rc="${HELP_MESSAGE_RC:-""}"
fzf_help_log "Custom help command is: $help_message_cmd"
fzf_help_log "Help message file is: $help_message"
fzf_help_log "Aliases: $help_message_rc"

if [ -f "$help_message_rc" ]; then
    shopt -s expand_aliases
    . "$help_message_rc"
fi
    

if [[ -n $cmd ]]; then
    if [[ -n $help_message_cmd ]]; then
        eval "$help_message_cmd" >"$help_message" || true
    else
        "$cmd" --help >"$help_message" || true
    fi
fi

cat "$help_message" > /dev/stdout
